name: minecraft-paper

services:
  minecraft:
    image: itzg/minecraft-server:2026.7.0-java21
    container_name: minecraft-paper

    restart: unless-stopped
    stop_grace_period: 2m
    stdin_open: true
    tty: true

    ports:
      - "25565:25565/tcp"

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.11"

      INIT_MEMORY: "2G"
      MAX_MEMORY: "4G"

      TZ: "Asia/Manila"
      ONLINE_MODE: "TRUE"

      MODE: "survival"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "10"
      VIEW_DISTANCE: "8"
      SIMULATION_DISTANCE: "6"

      MOTD: "Minecraft Azure Cloud | Paper 1.21.11"

      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"

      ENABLE_RCON: "TRUE"
      RCON_PASSWORD_FILE: "/run/secrets/rcon_password"

    volumes:
      - /srv/minecraft/data:/data

    secrets:
      - rcon_password

    mem_limit: 5g

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  rcon_password:
    file: ./secrets/rcon_password.txt